
// This file has been generated by the GUI designer. Do not modify.
namespace Recorder
{
	public partial class winSpectrum
	{
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Image image;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Recorder.winSpectrum
			this.Name = "Recorder.winSpectrum";
			this.Title = global::Mono.Unix.Catalog.GetString ("winSpectrum");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Recorder.winSpectrum.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image = new global::Gtk.Image ();
			this.image.Name = "image";
			this.fixed2.Add (this.image);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image]));
			w1.X = 23;
			w1.Y = 21;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();

		}
	}
}
